name: file_picker
description: A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support. !!based on https://github.com/miguelpruivo/plugins_flutter_file_picker, fix macos slecet file result is '/' problem.
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.alienhe.flutter.plugin.filepicker
    pluginClass: FilePickerPlugin
